<a href="https://colab.research.google.com/github/Harsh-Atkare/NumPy/blob/main/10__Random_Numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Random Number**

In [2]:
from numpy import random
# integer
a=random.randint(100)
print(a)

16


In [3]:
# float
a=random.rand()
print(a)
print("----------------------")
b=random.uniform(1,10)
print(b)

0.04242453131402213
----------------------
8.004055244828512


In [18]:
# random number from arrays
a=random.choice([1,2,3,4,5,6])
print(a)
print("----------------------")
a=random.choice([1,2,3,4,5,6],2)
print(a)

6
----------------------
[3 1]


In [5]:
# randomly shuffle in array
a=[1,2,3,4,5,6,7,8]
random.shuffle(a)
print(a)

[7, 6, 5, 1, 2, 8, 4, 3]


In [7]:
# number of unique numbers
rand_sample = random.sample(range(1, 100), 5)
print(rand_sample)  # Output: 5 unique random numbers between 1 and 99

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [8]:
# random array
print(random.__all__)

['beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf', 'Generator', 'RandomState', 'SeedSequence', 'MT19937', 'Philox', 'PCG64', 'PCG64DXSM', 'SFC64', 'default_rng', 'BitGenerator']


In [9]:
print(random.gumbel())

0.409173311304491


In [16]:
# Generate Random Array
d=random.randint(100,size=(5))
print(d)
print("--------------------------------------")
d=random.randint(100,size=(3,5)) # 3 rows and 5 values
print(d)
print("--------------------------------------")
d=random.rand(5)
print(d)
print("--------------------------------------")
d=random.rand(5,3) # 3 column and 5 rows
print(d)

[41 33 90 16 97]
--------------------------------------
[[92 98 13 91  5]
 [ 3  3 17 94 47]
 [81 71 20 38  0]]
--------------------------------------
[0.0574502  0.71963133 0.30288136 0.51454565 0.68306555]
--------------------------------------
[[0.67654121 0.39832572 0.62466617]
 [0.88092098 0.68111216 0.67262488]
 [0.53836625 0.0307016  0.6224538 ]
 [0.78151092 0.4775214  0.0303215 ]
 [0.9137097  0.15795074 0.37685588]]
