<a href="https://colab.research.google.com/github/Harsh-Atkare/NumPy/blob/main/4_Array_shapes_and__Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Shape
 the shape of an array refers to the dimensions of the array, expressed as a tuple of integers. It tells you the number of elements along each axis (dimension) of the array.

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [5]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [6]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3.shape)

(2, 2, 3)


## Reshaping
Reshaping in NumPy allows you to change the shape of an array without changing its data. You can transform the array into any shape that is compatible with its size (i.e., the total number of elements must remain the same).

In [8]:
# reshaping from 1d to 2d
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_c=c.reshape(4,3) # 4 row 3 column
print(reshaped_c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_c=c.reshape(2,3,2) # 4 block 3 row 2 column
print(reshaped_c)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
# converting multidiemention into 1 dim
f=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(f.shape)
f=f.flatten()
print(f.shape)
print(f)

(2, 2, 3)
(12,)
[1 2 3 1 2 3 1 2 3 1 2 3]
