<a href="https://colab.research.google.com/github/Harsh-Atkare/NumPy/blob/main/5_Array_Iterating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# looping

In [2]:
# looping in 1D
import numpy as np
a=np.array([1,2,3,4,5,13])
for i in a:
  print(i)

1
2
3
4
5
13


In [3]:
# looping i 2D
import numpy as np
b=np.array([[1,2,3],[6,5,4],[3,1,4]])
for i in b:
  print(i)

[1 2 3]
[6 5 4]
[3 1 4]


In [4]:
import numpy as np
b=np.array([[1,2,3],[6,5,4],[3,1,4]])
for i in b:
  for j in i:
    print(j)

1
2
3
6
5
4
3
1
4


In [9]:
# irtate 3D
import numpy as np
b=np.array([[[1,2,3],[6,5,4]],[[1,2,3],[6,5,4]]])
for i in b:
  print(b)

print("---------------------------------------")

for i in b:
  for j in i:
    print(j)

[[[1 2 3]
  [6 5 4]]

 [[1 2 3]
  [6 5 4]]]
[[[1 2 3]
  [6 5 4]]

 [[1 2 3]
  [6 5 4]]]
---------------------------------------
[1 2 3]
[6 5 4]
[1 2 3]
[6 5 4]


# nditer

nditer in NumPy is an efficient way to iterate over elements of an array. It simplifies looping through multi-dimensional arrays, allowing you to access each element without needing to write nested loops.

In [11]:
import numpy as np
b=np.array([[[1,2,3],[6,5,4]],[[1,2,3],[6,5,4]]])
for i in np.nditer(b):
  print(i)

1
2
3
6
5
4
1
2
3
6
5
4


In [31]:
import numpy as np
b=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for i in np.nditer(b[:,::2]):
  print(i)


1
2
3
7
8
9
