<a href="https://colab.research.google.com/github/Harsh-Atkare/NumPy/blob/main/6_Joining_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Joining array
joining arrays refers to combining multiple arrays into a single array. You can join arrays using several functions like concatenate(), stack(), hstack(), vstack(), and dstack().

In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [6]:
# joining 2D
a=np.array([[1,2,3],[7,6,5]])
b=np.array([[9,2,3],[88,6,5]])
result=np.concatenate((a,b),axis=0) # axis 0 means rows
print(result)
print("---------------------------------------")
result2=np.concatenate((a,b),axis=1) # and axis 1 means column
print(result2)

[[ 1  2  3]
 [ 7  6  5]
 [ 9  2  3]
 [88  6  5]]
---------------------------------------
[[ 1  2  3  9  2  3]
 [ 7  6  5 88  6  5]]


# Joining BY Stack

In [10]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.stack((a,b))
print(c)
print("---------------------------")
d=np.stack((a,b),axis=1)
print(d)
print("---------------------------")
e=np.stack((a,b),axis=0)
print(e)


[[1 2 3 4]
 [5 6 7 8]]
---------------------------
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
---------------------------
[[1 2 3 4]
 [5 6 7 8]]


# hstack


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))
result1 = np.vstack((arr1, arr2))
print(result)
print("-------------------------------")
print(result1)

[1 2 3 4 5 6]
-------------------------------
[[1 2 3]
 [4 5 6]]


In [12]:
a=np.array([[1,2,3],[7,6,5]])
b=np.array([[9,2,3],[88,6,5]])
result=np.hstack((a,b))
print(result)

[[ 1  2  3  9  2  3]
 [ 7  6  5 88  6  5]]
