<a href="https://colab.research.google.com/github/Harsh-Atkare/NumPy/blob/main/8_Searching_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Searching Array
Searching in a NumPy array allows you to find specific elements or their indices. NumPy provides various functions for this purpose, such as where(), searchsorted(), nonzero(), and extract()

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6,4, 7, 8, 9, 10])
index=np.where(arr==4)
print(index)
print(type(index))

(array([3, 6]),)
<class 'tuple'>


In [7]:
index=np.where(arr%2 == 0)
print(index)
print(index[0])
for i in index[0]:
  print(arr[i])

(array([ 1,  3,  5,  6,  8, 10]),)
[ 1  3  5  6  8 10]
2
4
6
4
8
10


# searchsorted()
The searchsorted() function finds the indices where elements should be inserted

In [10]:
import numpy as np

arr = np.array([6, 7, 9, 10])
index=np.searchsorted(arr, 8)
print(index)

2
