<a href="https://colab.research.google.com/github/Harsh-Atkare/NumPy/blob/main/9_sorting_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([6,5,2,4,1,7,4])
sorted=np.sort(a)
print(sorted)

[1 2 4 4 5 6 7]


In [5]:
# in 2D
a=np.array([[6,5,2],[4,1,7]])
sorted=np.sort(a)
print(sorted)


[[2 5 6]
 [1 4 7]]
